### ISSUE TITLE
proposal: ignore name pings at the end of a code eval block

### ISSUE THREAD

**Issue by dividinglimits** [raylu/sbot#15]
I would like for the following to evaluate the code and print the output of "a" (ignoring the name ping at the end)
```
lorem:
!js const a=1; a @lorem#42

sbot:
`1`
```

vs 
```
sbot:
``
```

**Comment by Walter-Sellars** [comment]
What's the reasoning behind needing to include the name ping inside the code block?

**Comment by dividinglimits** [comment]
I find it helpful to ping a response to someone for a question they may have asked. If sufficient time has passed and other messages have been going back and forth, I would need to execute the code block, then ping them in a separate line. This may be confusing or simply ignored
```
name: !py some code block

sbot:
`response`

name: @lorem#423 
```

As the responder, I would have to add additional context to the "ping" instead of just add it directly to the code block response

**Comment by raylu** [comment]
I think franz's question is "why support mentioning someone in the codeblock instead of having it outside the block? I think the parsing would be much simpler if we instead
1. continued parsing backtick-less invocations as the whole message is code
2. dropped anything outside of the code block when there are backticks

**Comment by dividinglimits** [comment]
I thing that's a decent thought, what I have in the PR does both. 
Question: I think it's becoming a bit hairy in the single back-tick scenario, such as the following.
```js
$ !js `const a=1; const dynStr = \`a is equal to ${a}\``
```
The parsing would now need an additional look-ahead regex. My PR already introduces re, so may be a non-issue, but something to consider. A mitigation is say that if someone wants to ping someone, they must the full code block (\`\`\`) syntax.

**Comment by raylu** [comment]
> I thing that's a decent thought, what I have in the PR does both.

I think we should definitely avoid doing both to simplify the code

> A mitigation is say that if someone wants to ping someone, they must the full code block (```) syntax.

yeah, that's my inclination too
