### ISSUE TITLE
bug: js code eval does not handle errors well

### ISSUE THREAD

**Issue by dividinglimits** [raylu/sbot#17]
```js
name: `try { throw new Error('a'); } catch { console.log(e) }`

sbot: 
``
```
https://github.com/raylu/sbot/blob/master/code_eval.py#L7:L29
Should also read from "stderr" and not just "stdout"

**Comment by raylu** [comment]
no, the error message is being logged to the console in your example, which is stdout

a nodejs upgrade caused an extra fork (when handling errors?) and it bumped up against my max pid limit
